# config.toml

# --- 全局设置 (所有数据集共用) ---
[common]
target_fs = 250         # 统一重采样到 250Hz
save_dir = "./output"   # 预处理结果保存路径
num_workers = 4

# --- 数据集定义 (列表形式) ---

# 数据集 1: MIT-BIH (使用 WFDB 格式)
[[datasets]]
name = "ecgid"
type = "wfdb"           # 对应代码中的 registry key
root_dir = "*"
channels = [0]          # 只读取第一个通道

# 数据集 2: PTB （使用 WFDB 格式）
# 平均心率，最低68，最高110
[[datasets]]
name = "ptb-ecg"
type = "wfdb"
sampling_rate = 1000
root_dir = "data/ptb"